version: 2

sources:
  - name: raw
    description: greenweez raw data source
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per product_id found in each order_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase
            tests:
              - not_null
          - name: orders_id
            description: the id for each order
            tests:
              - not_null
          - name: pdt_id
            description: the id of each product
            tests:
              - not_null
          - name: revenue
            description: unknown
            tests:
              - not_null
          - name: quantity
            description: quantity of products purchased per order per product_id
            tests:
              - not_null

      - name: product
        identifier: raw_gz_product
        description: the table associating each product's products_id with its purchase price
        columns:
          - name: products_id
            description: the id of the products
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: the price of a product
            tests:
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: the table describing for each order identified by its orders_id, the shipping_fee paid by the customer, ship_cost, and logcost logistic cost of the order
        columns:
          - name: orders_id
            description: the id of each order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the delivery fee paid by the customer
            tests:
              - not_null
          - name: logcost
            description: the logistic costs
            tests:
              - not_null
          - name: ship_cost
            description: the delivery fee
            tests:
              - not_null