version: 2

sources:
  - name: raw_data # Le nom du dataset BigQuery
    tables:
      - name: raw_gz_sales # La première table
      - name: raw_gz_product # La deuxième table
      - name: raw_gz_ship # La troisième table
